version: "3.8"

services:
  uat-augmont-voice-agents:
    container_name: uat-augmont-voice-agents
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3100:3000"
    env_file:
      - .env.uat
    restart: unless-stopped
    networks:
      - uat_default

networks:
  uat_default:
    external: true
