#!/bin/bash

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  Bolna Call Tracker - Quick Build & Run                  ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ Step 1: Dependencies Installed"
echo "✅ Step 2: .env File Created"
echo "✅ Step 3: All Code Files Ready"
echo ""
echo "⚠️  NEXT: Setup MongoDB & Get API Keys"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 CHECKLIST - Do These Now:"
echo ""
echo "1️⃣  MONGODB SETUP (Choose one):"
echo "   Option A: MongoDB Atlas (Recommended)"
echo "   ├─ Go to: https://www.mongodb.com/cloud/atlas"
echo "   ├─ Sign up FREE"
echo "   ├─ Create cluster (M0 free tier)"
echo "   ├─ Get connection string"
echo "   └─ Paste into .env as MONGODB_URI"
echo ""
echo "   Option B: Docker"
echo "   └─ docker run -d -p 27017:27017 --name mongodb mongo:latest"
echo ""
echo "2️⃣  GET BOLNA API KEY:"
echo "   ├─ Go to: https://platform.bolna.ai"
echo "   ├─ Login/Sign up"
echo "   ├─ Go to Developers section"
echo "   ├─ Generate API Key"
echo "   └─ Paste into .env as BOLNA_API_KEY"
echo ""
echo "3️⃣  CREATE BOLNA AGENT:"
echo "   ├─ Go to: https://platform.bolna.ai/agents"
echo "   ├─ Click Create Agent"
echo "   ├─ Fill in details (name, language, prompt)"
echo "   └─ Copy Agent ID (you'll need this)"
echo ""
echo "4️⃣  EDIT .env FILE:"
echo "   nano .env"
echo ""
echo "   Then set:"
echo "   MONGODB_URI=<your_mongodb_connection>"
echo "   BOLNA_API_KEY=<your_api_key>"
echo ""
echo "5️⃣  START SERVER:"
echo "   npm run dev"
echo ""
echo "6️⃣  OPEN DASHBOARD:"
echo "   http://localhost:5000"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
