import { useState, useEffect } from "react"
import { api } from "@/lib/api"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import {
  Plus, Trash2, ChevronUp, ChevronDown, Save, FileText,
  Edit2, X, Check, ArrowLeft, Loader2
} from "lucide-react"

// ── Constants ─────────────────────────────────────────────────────────────────

const SOURCE_OPTIONS = [
  { value: "transcript_extract", label: "AI Extract from Transcript" },
  { value: "call_field",         label: "Call Field" },
  { value: "customer_field",     label: "Customer Field" },
  { value: "bolna_variable",     label: "Bolna Variable" },
  { value: "static",             label: "Static Value" },
]

const CALL_FIELD_OPTIONS = [
  { value: "status",             label: "Call Status" },
  { value: "duration",           label: "Duration" },
  { value: "call_start_time",    label: "Call Start Time" },
  { value: "call_end_time",      label: "Call End Time" },
  { value: "created_at",         label: "Created At" },
  { value: "agent_name",         label: "Agent Name" },
  { value: "agent_id",           label: "Agent ID" },
  { value: "phone_number",       label: "Phone Number" },
  { value: "outcome",            label: "Outcome / Summary" },
  { value: "notes",              label: "Hangup Reason / Notes" },
  { value: "recording_url",      label: "Recording URL" },
  { value: "error_message",      label: "Error Message" },
  { value: "language",           label: "Language" },
  { value: "bolna_execution_id", label: "Bolna Execution ID" },
  { value: "transferred",        label: "Transferred to Agent" },
  { value: "transferred_agent",  label: "Transferred Agent Name" },
]

const CUSTOMER_FIELD_OPTIONS = [
  { value: "name",     label: "Name" },
  { value: "phoneNumber", label: "Phone" },
  { value: "email",    label: "Email" },
  { value: "language", label: "Language" },
  { value: "notes",    label: "Notes" },
  { value: "status",   label: "Status" },
]

function newField() {
  return {
    key: "",
    label: "",
    source: "transcript_extract",
    extractionPrompt: "",
    callField: "status",
    customerField: "name",
    bolnaKey: "",
    staticValue: "",
    defaultValue: "",
  }
}

// ── Field Editor Row ──────────────────────────────────────────────────────────

function FieldRow({ field, index, total, onChange, onRemove, onMoveUp, onMoveDown }) {
  const [expanded, setExpanded] = useState(false)

  return (
    <div className="border border-gray-200 rounded-lg bg-white">
      {/* Summary row */}
      <div className="flex items-center gap-2 px-3 py-2">
        <div className="flex flex-col gap-0.5">
          <button onClick={onMoveUp}  disabled={index === 0}       className="text-gray-400 hover:text-gray-600 disabled:opacity-30"><ChevronUp size={14}/></button>
          <button onClick={onMoveDown} disabled={index === total-1} className="text-gray-400 hover:text-gray-600 disabled:opacity-30"><ChevronDown size={14}/></button>
        </div>

        <span className="w-6 h-6 flex items-center justify-center rounded-full bg-[#18120E] text-white text-xs font-bold flex-shrink-0">
          {index + 1}
        </span>

        <div className="flex-1 grid grid-cols-2 gap-2 min-w-0">
          <div>
            <Input
              placeholder="Column name (e.g. Current CTC)"
              value={field.label}
              onChange={e => {
                const label = e.target.value
                const autoKey = label.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '')
                // Only auto-update key if user hasn't manually edited it
                const prevAutoKey = field.label.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '')
                const keyWasAutoGenerated = field.key === prevAutoKey || field.key === ''
                onChange({ ...field, label, key: keyWasAutoGenerated ? autoKey : field.key })
              }}
              className="text-sm h-8"
            />
            {field.key && (
              <p className="text-[10px] text-gray-400 mt-0.5 font-mono pl-1">key: {field.key}</p>
            )}
          </div>
          <select
            value={field.source}
            onChange={e => onChange({ ...field, source: e.target.value })}
            className="text-sm h-8 border border-gray-200 rounded-md px-2 bg-white"
          >
            {SOURCE_OPTIONS.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
          </select>
        </div>

        <button
          onClick={() => setExpanded(v => !v)}
          className="text-gray-400 hover:text-[#18120E] text-xs px-2 py-1 rounded border border-gray-200 flex-shrink-0"
        >
          {expanded ? "Less" : "More"}
        </button>
        <button onClick={onRemove} className="text-red-400 hover:text-red-600 flex-shrink-0">
          <Trash2 size={14}/>
        </button>
      </div>

      {/* Expanded options */}
      {expanded && (
        <div className="px-3 pb-3 border-t border-gray-100 pt-2 space-y-2">
          <div>
            <label className="text-xs text-gray-500 mb-1 block">Column key <span className="text-gray-400">(auto-generated — edit only if needed)</span></label>
            <Input
              placeholder="e.g. current_ctc"
              value={field.key}
              onChange={e => onChange({ ...field, key: e.target.value.replace(/\s+/g, '_').toLowerCase() })}
              className="text-sm h-8 font-mono"
            />
          </div>
          {field.source === "transcript_extract" && (
            <div>
              <label className="text-xs text-gray-500 mb-1 block">Extraction prompt (tells GPT what to look for)</label>
              <Textarea
                placeholder={`e.g. What is the candidate's current CTC or salary? Return a short value like '12 LPA'. If not mentioned, return 'Not disclosed'.`}
                value={field.extractionPrompt}
                onChange={e => onChange({ ...field, extractionPrompt: e.target.value })}
                className="text-sm min-h-[60px]"
              />
            </div>
          )}
          {field.source === "call_field" && (
            <div>
              <label className="text-xs text-gray-500 mb-1 block">Call field</label>
              <select
                value={field.callField}
                onChange={e => onChange({ ...field, callField: e.target.value })}
                className="text-sm h-8 border border-gray-200 rounded-md px-2 bg-white w-full"
              >
                {CALL_FIELD_OPTIONS.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
              </select>
            </div>
          )}
          {field.source === "customer_field" && (
            <div>
              <label className="text-xs text-gray-500 mb-1 block">Customer field</label>
              <select
                value={field.customerField}
                onChange={e => onChange({ ...field, customerField: e.target.value })}
                className="text-sm h-8 border border-gray-200 rounded-md px-2 bg-white w-full"
              >
                {CUSTOMER_FIELD_OPTIONS.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
              </select>
            </div>
          )}
          {field.source === "bolna_variable" && (
            <div>
              <label className="text-xs text-gray-500 mb-1 block">Bolna variable key</label>
              <Input
                placeholder="e.g. interest_level"
                value={field.bolnaKey}
                onChange={e => onChange({ ...field, bolnaKey: e.target.value })}
                className="text-sm h-8"
              />
            </div>
          )}
          {field.source === "static" && (
            <div>
              <label className="text-xs text-gray-500 mb-1 block">Static value</label>
              <Input
                placeholder="e.g. HR Screening"
                value={field.staticValue}
                onChange={e => onChange({ ...field, staticValue: e.target.value })}
                className="text-sm h-8"
              />
            </div>
          )}
          <div>
            <label className="text-xs text-gray-500 mb-1 block">Default value (if empty)</label>
            <Input
              placeholder="e.g. Not provided"
              value={field.defaultValue}
              onChange={e => onChange({ ...field, defaultValue: e.target.value })}
              className="text-sm h-8"
            />
          </div>
        </div>
      )}
    </div>
  )
}

// ── Template Editor ───────────────────────────────────────────────────────────

function TemplateEditor({ template, agents, onSave, onBack }) {
  const isNew = !template.templateId
  const [name, setName] = useState(template.name || "")
  const [agentId, setAgentId] = useState(template.agentId || "")
  const [fields, setFields] = useState(template.fields || [])
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState("")

  const addField = () => setFields(f => [...f, newField()])

  const updateField = (i, updated) => setFields(f => f.map((x, idx) => idx === i ? updated : x))
  const removeField = (i) => setFields(f => f.filter((_, idx) => idx !== i))
  const moveUp   = (i) => { if (i === 0) return; const a = [...fields]; [a[i-1], a[i]] = [a[i], a[i-1]]; setFields(a) }
  const moveDown = (i) => { if (i === fields.length-1) return; const a = [...fields]; [a[i], a[i+1]] = [a[i+1], a[i]]; setFields(a) }

  const save = async () => {
    if (!name.trim()) { setError("Template name is required"); return }
    if (fields.some(f => !f.key || !f.label)) { setError("All fields need a key and label"); return }
    setError("")
    setSaving(true)
    await onSave({ name: name.trim(), agentId: agentId || null, fields })
    setSaving(false)
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-3">
        <Button variant="outline" size="sm" onClick={onBack}><ArrowLeft size={14} className="mr-1"/> Back</Button>
        <h3 className="text-lg font-semibold text-[#18120E]">{isNew ? "New Template" : `Edit: ${template.name}`}</h3>
      </div>

      {error && (
        <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-2 rounded-lg text-sm">{error}</div>
      )}

      <Card>
        <CardContent className="p-4 space-y-3">
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="text-xs font-medium text-gray-600 mb-1 block">Template Name *</label>
              <Input
                placeholder="e.g. HR Initial Screening"
                value={name}
                onChange={e => setName(e.target.value)}
              />
            </div>
            <div>
              <label className="text-xs font-medium text-gray-600 mb-1 block">Bind to Agent (optional)</label>
              <select
                value={agentId}
                onChange={e => setAgentId(e.target.value)}
                className="w-full h-10 border border-gray-200 rounded-md px-3 text-sm bg-white"
              >
                <option value="">All agents</option>
                {agents.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}
              </select>
            </div>
          </div>
        </CardContent>
      </Card>

      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <h4 className="font-medium text-gray-700 text-sm">Fields ({fields.length})</h4>
          <div className="text-xs text-gray-400 hidden sm:block">Column Name · Source</div>
        </div>

        {fields.length === 0 && (
          <div className="border-2 border-dashed border-gray-200 rounded-lg py-8 text-center text-sm text-gray-400">
            No fields yet. Add your first field below.
          </div>
        )}

        {fields.map((f, i) => (
          <FieldRow
            key={i}
            field={f}
            index={i}
            total={fields.length}
            onChange={updated => updateField(i, updated)}
            onRemove={() => removeField(i)}
            onMoveUp={() => moveUp(i)}
            onMoveDown={() => moveDown(i)}
          />
        ))}

        <Button variant="outline" onClick={addField} className="w-full border-dashed text-gray-500">
          <Plus size={14} className="mr-2"/> Add Field
        </Button>
      </div>

      <div className="flex justify-end pt-2">
        <Button
          onClick={save}
          disabled={saving}
          className="bg-[#18120E] hover:bg-[#024a5e] text-white"
        >
          {saving ? <Loader2 size={14} className="mr-2 animate-spin"/> : <Save size={14} className="mr-2"/>}
          {saving ? "Saving…" : "Save Template"}
        </Button>
      </div>
    </div>
  )
}

// ── Main Page ─────────────────────────────────────────────────────────────────

export function ReportTemplates() {
  const [templates, setTemplates] = useState([])
  const [agents, setAgents] = useState([])
  const [loading, setLoading] = useState(true)
  const [editing, setEditing] = useState(null)   // null = list, object = editor
  const [deleting, setDeleting] = useState(null)

  const load = async () => {
    const [t, a] = await Promise.all([api.getReportTemplates(), api.getAgents()])
    setTemplates(t.data || [])
    setAgents(a.data || [])
    setLoading(false)
  }

  useEffect(() => { load() }, [])

  const handleSave = async (payload) => {
    if (editing.templateId) {
      await api.updateReportTemplate(editing.templateId, payload)
    } else {
      await api.createReportTemplate(payload)
    }
    await load()
    setEditing(null)
  }

  const handleDelete = async (templateId) => {
    setDeleting(templateId)
    await api.deleteReportTemplate(templateId)
    await load()
    setDeleting(null)
  }

  if (loading) return <div className="text-center py-20 text-gray-400">Loading…</div>

  if (editing !== null) {
    return (
      <TemplateEditor
        template={editing}
        agents={agents}
        onSave={handleSave}
        onBack={() => setEditing(null)}
      />
    )
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-[#18120E]">Report Templates</h2>
          <p className="text-sm text-gray-500 mt-0.5">Define which fields to export per agent / use-case</p>
        </div>
        <Button
          onClick={() => setEditing({ name: "", agentId: "", fields: [] })}
          className="bg-[#18120E] hover:bg-[#024a5e] text-white"
        >
          <Plus size={14} className="mr-2"/> New Template
        </Button>
      </div>

      {templates.length === 0 ? (
        <Card>
          <CardContent className="py-16 text-center">
            <FileText size={40} className="mx-auto mb-3 text-gray-300"/>
            <p className="text-gray-500 text-sm">No templates yet.</p>
            <p className="text-gray-400 text-xs mt-1">Create a template to define what columns appear in your exported reports.</p>
            <Button
              onClick={() => setEditing({ name: "", agentId: "", fields: [] })}
              className="mt-4 bg-[#18120E] hover:bg-[#024a5e] text-white"
            >
              <Plus size={14} className="mr-2"/> Create First Template
            </Button>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-2">
          {templates.map(t => {
            const fieldCount = (t.fields || []).length
            const agentName = t.agentId ? agents.find(a => a.id === t.agentId)?.name || t.agentId : null
            return (
              <Card key={t.templateId} className="hover:shadow-md transition-shadow">
                <CardContent className="p-4 flex items-center gap-4">
                  <div className="w-10 h-10 bg-[#18120E]/10 rounded-lg flex items-center justify-center flex-shrink-0">
                    <FileText size={18} className="text-[#18120E]"/>
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="font-semibold text-gray-800 truncate">{t.name}</p>
                    <div className="flex items-center gap-3 mt-0.5">
                      <span className="text-xs text-gray-500">{fieldCount} field{fieldCount !== 1 ? "s" : ""}</span>
                      {agentName
                        ? <span className="text-xs bg-blue-50 text-blue-700 border border-blue-200 rounded-full px-2 py-0.5">{agentName}</span>
                        : <span className="text-xs text-gray-400">All agents</span>
                      }
                    </div>
                  </div>
                  <div className="flex gap-2">
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => setEditing(t)}
                    >
                      <Edit2 size={13} className="mr-1"/> Edit
                    </Button>
                    <Button
                      variant="outline"
                      size="sm"
                      disabled={deleting === t.templateId}
                      onClick={() => {
                        if (confirm(`Delete template "${t.name}"? This cannot be undone.`)) {
                          handleDelete(t.templateId)
                        }
                      }}
                      className="text-red-500 border-red-200 hover:bg-red-50"
                    >
                      {deleting === t.templateId
                        ? <Loader2 size={13} className="animate-spin"/>
                        : <Trash2 size={13}/>
                      }
                    </Button>
                  </div>
                </CardContent>
              </Card>
            )
          })}
        </div>
      )}

      {/* Quick-reference: field source legend */}
      <div className="mt-6 border border-gray-200 rounded-lg p-4 bg-gray-50">
        <p className="text-xs font-semibold text-gray-500 mb-2 uppercase tracking-wide">Field Source Guide</p>
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-2 text-xs text-gray-600">
          <div><span className="font-semibold text-purple-700">AI Extract</span> — GPT reads transcript, cached after first export</div>
          <div><span className="font-semibold text-blue-700">Call Field</span> — status, duration, timestamps, outcome, etc.</div>
          <div><span className="font-semibold text-teal-700">Customer Field</span> — name, phone, email from customer record</div>
          <div><span className="font-semibold text-amber-700">Bolna Variable</span> — structured data Bolna captured during the call</div>
          <div><span className="font-semibold text-gray-700">Static Value</span> — fixed text in every row (e.g. campaign name)</div>
        </div>
      </div>
    </div>
  )
}
